config/routes.rb
Rails.application.routes.draw do
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :categories do
    resources :articles
  end

  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category
  before_create :create_key

  validates :title,
            :description,
            :price,
              presence: true

  def create_key
    charset = Array('a'..'z') + Array(0..9)
    code = Array.new(6) { charset.sample }.join
    self.key = code
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles

  validates :username, uniqueness: { scope: :email}
  validates :username,
            :email,
              presence: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end

  private
    def article_params
      params.require(:article).permit(:title, :description, :price, :category_id, :user_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user =  User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Thanks for signing up!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||=User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def require_user
    redirect '/login' unless logged_in?
  end

  def log_out
    session.clear
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/show.html.erb
<div class="container">
	<h1><%= @article.title %> - $<%= @article.price %></h1>

	<h2>Description:</h2>
	<p><%= @article.description %></p>

	<h2>Contact information</h2>
	<p><%= @article.user.email %></p>
	<p><%= @article.user.phone %></p>

	<p>Created at:</p>
	<p><%= @article.created_at %></p>
	<p>Last updated:</p>
	<p><%= @article.updated_at %></p>

	<% if @key %>
		<h2>Edit key</h2>
		<p>Use this key to edit your article</p>
		<p> <%= @key %></p>
		<p>Example</p>
		<p><a href="articles/<%= @article.id %>/edit/<%=@key %>">http://localhost:3000/articles/<%= @article.id %>/edit/<%=@key %></a></p>
	<% end %>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>

<% if @categories %>
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category_path(category) do %><%= category.name %><% end %></li>
  <% end %>
</ul>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<% if @category %>
  <ul>
    <% @category.articles.each do |article| %>
    <li><a href="/categories/<%= @category.id %>/articles/<%= article.id %>"><%= article.title %></a></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Claire's List", '/', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '/' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% else %>
            <li><%= link_to "Register", register_path %></li>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Claire's List</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render '/layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<p>User since: <%= @user.created_at%></p>

<h2>Posts Created:</h2>
<% if @user.articles %>
<ul>
  <% @user.articles.each do |article| %>
    <li><strong><%= article.title %></strong><br>
      <%= article.created_at %><br>
      <%= article.description %>
    </li>
  <% end %>
</ul>
<% end %>